# Generated by Django 4.0.5 on 2022-06-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=148)),
                ('cedula', models.CharField(max_length=148)),
                ('correo', models.EmailField(max_length=148)),
                ('contrasena', models.CharField(max_length=148)),
            ],
        ),
    ]
