# Generated by Django 4.0.5 on 2022-06-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=148)),
                ('cedula', models.CharField(max_length=148)),
                ('correo', models.EmailField(max_length=148)),
                ('contrasena', models.CharField(max_length=148)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=148)),
                ('cedula', models.CharField(max_length=148)),
                ('correo', models.EmailField(max_length=148)),
                ('contrasena', models.CharField(max_length=148)),
            ],
        ),
    ]
